### ISSUE TITLE
macOS 10.15 syscall.Mprotect panic: permission denied

### ISSUE THREAD

**Issue by luckyzachary** [agiledragon/gomonkey#10]
Hi:
     After I was update my macOS to about 10.14, It will report panic: permission denied when I run ApplyFunc or ApplyMethod. I searched this problem in google, but I don't have answer. Which permission I should set?
      Thanks a lot. 
      This is panic stack.
------
panic: permission denied [recovered]
        panic: permission denied

goroutine 13 [running]:
testing.tRunner.func1(0xc4202081e0)
        /.../goroot/go/src/testing/testing.go:742 +0x29d
panic(0x4e697e0, 0xc4205a7c18)
        /.../goroot/go/src/runtime/panic.go:502 +0x229
github.com/agiledragon/gomonkey.modifyBinary(0x4bf4570, 0xc420229a7c, 0xc, 0xc)
        /.../gopath/src/github.com/agiledragon/gomonkey/modify_binary_darwin.go:11 +0x198
github.com/agiledragon/gomonkey.replace(0x4bf4570, 0x5099668, 0xc420229b58, 0x59aa580, 0x4dd7500)
        /.../gopath/src/github.com/agiledragon/gomonkey/patch.go:164 +0x112
github.com/agiledragon/gomonkey.(*Patches).applyCore(0xc420086c40, 0x4dd7560, 0x5099ba8, 0x13, 0x4dd7560, 0x5099668, 0x13, 0x10)
        /.../gopath/src/github.com/agiledragon/gomonkey/patch.go:140 +0x161
github.com/agiledragon/gomonkey.(*Patches).ApplyFunc(0xc420086c40, 0x4dd7560, 0x5099ba8, 0x4dd7560, 0x5099668, 0x4009d7d)
        /.../gopath/src/github.com/agiledragon/gomonkey/patch.go:60 +0xbf
github.com/agiledragon/gomonkey.ApplyFunc(0x4dd7560, 0x5099ba8, 0x4dd7560, 0x5099668, 0x2ae)
        /.../gopath/src/github.com/agiledragon/gomonkey/patch.go:22 +0xa2

**Comment by agiledragon** [comment]
My Mac OS is 10.13.6, it has no this problem

**Comment by zhengjilei** [comment]
I came across the same problem on macOS 10.15.1

**Comment by zhengjilei** [comment]
> ## Hi:
> After I was update my macOS to about 10.14, It will report panic: permission denied when I run ApplyFunc or ApplyMethod. I searched this problem in google, but I don't have answer. Which permission I should set?
> Thanks a lot.
> This is panic stack.
> panic: permission denied [recovered]
> panic: permission denied
> 
> goroutine 13 [running]:
> testing.tRunner.func1(0xc4202081e0)
> /.../goroot/go/src/testing/testing.go:742 +0x29d
> panic(0x4e697e0, 0xc4205a7c18)
> /.../goroot/go/src/runtime/panic.go:502 +0x229
> github.com/agiledragon/gomonkey.modifyBinary(0x4bf4570, 0xc420229a7c, 0xc, 0xc)
> /.../gopath/src/github.com/agiledragon/gomonkey/modify_binary_darwin.go:11 +0x198
> github.com/agiledragon/gomonkey.replace(0x4bf4570, 0x5099668, 0xc420229b58, 0x59aa580, 0x4dd7500)
> /.../gopath/src/github.com/agiledragon/gomonkey/patch.go:164 +0x112
> github.com/agiledragon/gomonkey.(*Patches).applyCore(0xc420086c40, 0x4dd7560, 0x5099ba8, 0x13, 0x4dd7560, 0x5099668, 0x13, 0x10)
> /.../gopath/src/github.com/agiledragon/gomonkey/patch.go:140 +0x161
> github.com/agiledragon/gomonkey.(*Patches).ApplyFunc(0xc420086c40, 0x4dd7560, 0x5099ba8, 0x4dd7560, 0x5099668, 0x4009d7d)
> /.../gopath/src/github.com/agiledragon/gomonkey/patch.go:60 +0xbf
> github.com/agiledragon/gomonkey.ApplyFunc(0x4dd7560, 0x5099ba8, 0x4dd7560, 0x5099668, 0x2ae)
> /.../gopath/src/github.com/agiledragon/gomonkey/patch.go:22 +0xa2

I came across the same problem on macOS 10.15.1, did you solve it? could you plz give me some hints to solve this?

**Comment by zhengjilei** [comment]
> ## Hi:
> After I was update my macOS to about 10.14, It will report panic: permission denied when I run ApplyFunc or ApplyMethod. I searched this problem in google, but I don't have answer. Which permission I should set?
> Thanks a lot.
> This is panic stack.
> panic: permission denied [recovered]
> panic: permission denied
> 
> goroutine 13 [running]:
> testing.tRunner.func1(0xc4202081e0)
> /.../goroot/go/src/testing/testing.go:742 +0x29d
> panic(0x4e697e0, 0xc4205a7c18)
> /.../goroot/go/src/runtime/panic.go:502 +0x229
> github.com/agiledragon/gomonkey.modifyBinary(0x4bf4570, 0xc420229a7c, 0xc, 0xc)
> /.../gopath/src/github.com/agiledragon/gomonkey/modify_binary_darwin.go:11 +0x198
> github.com/agiledragon/gomonkey.replace(0x4bf4570, 0x5099668, 0xc420229b58, 0x59aa580, 0x4dd7500)
> /.../gopath/src/github.com/agiledragon/gomonkey/patch.go:164 +0x112
> github.com/agiledragon/gomonkey.(*Patches).applyCore(0xc420086c40, 0x4dd7560, 0x5099ba8, 0x13, 0x4dd7560, 0x5099668, 0x13, 0x10)
> /.../gopath/src/github.com/agiledragon/gomonkey/patch.go:140 +0x161
> github.com/agiledragon/gomonkey.(*Patches).ApplyFunc(0xc420086c40, 0x4dd7560, 0x5099ba8, 0x4dd7560, 0x5099668, 0x4009d7d)
> /.../gopath/src/github.com/agiledragon/gomonkey/patch.go:60 +0xbf
> github.com/agiledragon/gomonkey.ApplyFunc(0x4dd7560, 0x5099ba8, 0x4dd7560, 0x5099668, 0x2ae)
> /.../gopath/src/github.com/agiledragon/gomonkey/patch.go:22 +0xa2

hi bro, I came across the same problem too on macOS Catalina,  did you solve this? Could you plz give me some hints to solve it?

**Comment by cheaterlin** [comment]
> My Mac OS is 10.13.6, it has no this problem.
> You can try it with the root user.

Catalina(10.15.2) has this problem. Sudo can't solve the problem

**Comment by kakisong** [comment]
does anybody figure this out

**Comment by itaymeller** [comment]
getting the same problem as well. anyone solved it?

**Comment by abhineet-plivo** [comment]
I am also facing this issue any idea what's the resolution?

**Comment by larryyu2** [comment]
me too

**Comment by larryyu2** [comment]
I don't know how to fix this ,but I found a way to solve this.
Use the docker with official golang image, map your gopath to the container's gopath, then in the container's terminal, you can run the tests likes in your mac.

**Comment by kiyonlin** [comment]
When I upgraded the go version to 1.14.1, there was no longer a "permission denied" situation.

**Comment by hello2mao** [comment]
+1
macos 10.15.4
go version go1.14.2 darwin/amd64

**Comment by heqianwu** [comment]
what's the resolution?
go1.2.4 + MacOS10.15.4 is OK.
while go1.13.5 + MacOS10.15.4 has this problem.
maybe go1.13.5 + MacOS10.13.x/MacOS10.14.x work well.

**Comment by agiledragon** [comment]
// modify_binary_darwin.go
err := syscall.Mprotect(page, syscall.PROT_READ|syscall.PROT_WRITE|syscall.PROT_EXEC)

If your  macOS is  Catalina 10.15.x, please try to replace "err := syscall.Mprotect(page, syscall.PROT_READ|syscall.PROT_WRITE|syscall.PROT_EXEC)" with "err := syscall.Mprotect(page, syscall.PROT_READ|syscall.PROT_WRITE)" or "err := syscall.Mprotect(page, syscall.PROT_WRITE)".

**Comment by tobegit3hub** [comment]
Please try `printf '\x07' | dd of=<executable> bs=1 seek=160 count=1 conv=notrunc`.

Refer to https://stackoverflow.com/questions/60654834/using-mprotect-to-make-text-segment-writable-on-macos .

**Comment by agiledragon** [comment]
> Please try `printf '\x07' | dd of=<executable> bs=1 seek=160 count=1 conv=notrunc`.
> 
> Refer to https://stackoverflow.com/questions/60654834/using-mprotect-to-make-text-segment-writable-on-macos .

Does anyone try this?

**Comment by brzyangg** [comment]
> > Please try `printf '\x07' | dd of=<executable> bs=1 seek=160 count=1 conv=notrunc`.
> > Refer to https://stackoverflow.com/questions/60654834/using-mprotect-to-make-text-segment-writable-on-macos .
> 
> Does anyone try this？

I don't know how to set `<executable>`

**Comment by liaoishere** [comment]
> > Please try `printf '\x07' | dd of=<executable> bs=1 seek=160 count=1 conv=notrunc`.
> > Refer to https://stackoverflow.com/questions/60654834/using-mprotect-to-make-text-segment-writable-on-macos .
> 
> Does anyone try this?

It works on my Mac with macOS 10.15.5.

> > > Please try `printf '\x07' | dd of=<executable> bs=1 seek=160 count=1 conv=notrunc`.
> > > Refer to https://stackoverflow.com/questions/60654834/using-mprotect-to-make-text-segment-writable-on-macos .
> > 
> > 
> > Does anyone try this？
> 
> I don't know how to set `<executable>`

go test actually includes three steps:
1. compile the test functions into a binary
2. execute the binary
3. delete the binary

we need to first generate the test binary , the dd the compiled binary file. e.g.:

```
$ go test -c -o test-bin mytest/abc
```
With `-c` and `-o` option, go test will generate a binary named test-bin. Then modify the binary with dd according to https://stackoverflow.com/questions/60654834/using-mprotect-to-make-text-segment-writable-on-macos#:

```
$  printf '\x07' | dd of=test-bin bs=1 seek=160 count=1 conv=notrunc
```

Finally, you can run the test binary:

```
./test-bin
```

**Comment by LaryCaka** [comment]
> // modify_binary_darwin.go
> err := syscall.Mprotect(page, syscall.PROT_READ|syscall.PROT_WRITE|syscall.PROT_EXEC)
> 
> If your macOS is Catalina 10.15.x, please try to replace "err := syscall.Mprotect(page, syscall.PROT_READ|syscall.PROT_WRITE|syscall.PROT_EXEC)" with "err := syscall.Mprotect(page, syscall.PROT_READ|syscall.PROT_WRITE)" or "err := syscall.Mprotect(page, syscall.PROT_WRITE)".

 i try this  ,but i can't solve the problem,

**Comment by agiledragon** [comment]
> > // modify_binary_darwin.go
> > err := syscall.Mprotect(page, syscall.PROT_READ|syscall.PROT_WRITE|syscall.PROT_EXEC)
> > If your macOS is Catalina 10.15.x, please try to replace "err := syscall.Mprotect(page, syscall.PROT_READ|syscall.PROT_WRITE|syscall.PROT_EXEC)" with "err := syscall.Mprotect(page, syscall.PROT_READ|syscall.PROT_WRITE)" or "err := syscall.Mprotect(page, syscall.PROT_WRITE)".
> 
> i try this ,but i can't solve the problem,

There are two methods:

1. Use the docker with official golang image, map your gopath to the container's gopath, then in the container's terminal, you can run the tests likes in your mac.

2. A brute workaround is to manually modify and set __TEXT(max_prot) to 0x7 after linking.
printf '\x07' | dd of=<executable> bs=1 seek=160 count=1 conv=notrunc
Refer to https://stackoverflow.com/questions/60654834/using-mprotect-to-make-text-segment-writable-on-macos .

**Comment by zhangzhen8230** [comment]
> > > Please try `printf '\x07' | dd of=<executable> bs=1 seek=160 count=1 conv=notrunc`.
> > > Refer to https://stackoverflow.com/questions/60654834/using-mprotect-to-make-text-segment-writable-on-macos .
> > 
> > 
> > Does anyone try this?
> 
> It works on my Mac with macOS 10.15.5.
> 
> > > > Please try `printf '\x07' | dd of=<executable> bs=1 seek=160 count=1 conv=notrunc`.
> > > > Refer to https://stackoverflow.com/questions/60654834/using-mprotect-to-make-text-segment-writable-on-macos .
> > > 
> > > 
> > > Does anyone try this？
> > 
> > 
> > I don't know how to set `<executable>`
> 
> go test actually includes three steps:
> 
> 1. compile the test functions into a binary
> 2. execute the binary
> 3. delete the binary
> 
> To work around this issue, we need to first generate the test binary, the modify the compiled binary with dd. e.g.
> 
> ```
> $ go test -c -o test-bin mytest/abc
> ```
> 
> With `-c` and `-o` option, go test will generate a binary named test-bin. Then modify the binary with dd according to https://stackoverflow.com/questions/60654834/using-mprotect-to-make-text-segment-writable-on-macos#:
> 
> ```
> $  printf '\x07' | dd of=test-bin bs=1 seek=160 count=1 conv=notrunc
> ```
> 
> Finally, you can run the test binary:
> 
> ```
> ./test-bin
> ```

can solve the problem,But it's too cumbersome to execute every time

**Comment by kamly** [comment]
> > > > Please try `printf '\x07' | dd of=<executable> bs=1 seek=160 count=1 conv=notrunc`.
> > > > Refer to https://stackoverflow.com/questions/60654834/using-mprotect-to-make-text-segment-writable-on-macos .
> > > 
> > > 
> > > Does anyone try this?
> > 
> > 
> > It works on my Mac with macOS 10.15.5.
> > > > > Please try `printf '\x07' | dd of=<executable> bs=1 seek=160 count=1 conv=notrunc`.
> > > > > Refer to https://stackoverflow.com/questions/60654834/using-mprotect-to-make-text-segment-writable-on-macos .
> > > > 
> > > > 
> > > > Does anyone try this？
> > > 
> > > 
> > > I don't know how to set `<executable>`
> > 
> > 
> > go test actually includes three steps:
> > 
> > 1. compile the test functions into a binary
> > 2. execute the binary
> > 3. delete the binary
> > 
> > To work around this issue, we need to first generate the test binary, the modify the compiled binary with dd. e.g.
> > ```
> > $ go test -c -o test-bin mytest/abc
> > ```
> > 
> > 
> > With `-c` and `-o` option, go test will generate a binary named test-bin. Then modify the binary with dd according to https://stackoverflow.com/questions/60654834/using-mprotect-to-make-text-segment-writable-on-macos#:
> > ```
> > $  printf '\x07' | dd of=test-bin bs=1 seek=160 count=1 conv=notrunc
> > ```
> > 
> > 
> > Finally, you can run the test binary:
> > ```
> > ./test-bin
> > ```
> 
> can solve the problem,But it's too cumbersome to execute every time
> 
> So，It is recommended to use docker to solve this problem。

i also meet the problem and use this method `printf '\x07' | dd of=test-bin bs=1 seek=160 count=1 conv=notrunc` fix it .

but i want to know that if gomonkey can fix it ?

**Comment by newjunwei** [comment]
> > > > > Please try `printf '\x07' | dd of=<executable> bs=1 seek=160 count=1 conv=notrunc`.
> > > > > Refer to https://stackoverflow.com/questions/60654834/using-mprotect-to-make-text-segment-writable-on-macos .
> > > > 
> > > > 
> > > > Does anyone try this?
> > > 
> > > 
> > > It works on my Mac with macOS 10.15.5.
> > > > > > Please try `printf '\x07' | dd of=<executable> bs=1 seek=160 count=1 conv=notrunc`.
> > > > > > Refer to https://stackoverflow.com/questions/60654834/using-mprotect-to-make-text-segment-writable-on-macos .
> > > > > 
> > > > > 
> > > > > Does anyone try this？
> > > > 
> > > > 
> > > > I don't know how to set `<executable>`
> > > 
> > > 
> > > go test actually includes three steps:
> > > 
> > > 1. compile the test functions into a binary
> > > 2. execute the binary
> > > 3. delete the binary
> > > 
> > > To work around this issue, we need to first generate the test binary, the modify the compiled binary with dd. e.g.
> > > ```
> > > $ go test -c -o test-bin mytest/abc
> > > ```
> > > 
> > > 
> > > With `-c` and `-o` option, go test will generate a binary named test-bin. Then modify the binary with dd according to https://stackoverflow.com/questions/60654834/using-mprotect-to-make-text-segment-writable-on-macos#:
> > > ```
> > > $  printf '\x07' | dd of=test-bin bs=1 seek=160 count=1 conv=notrunc
> > > ```
> > > 
> > > 
> > > Finally, you can run the test binary:
> > > ```
> > > ./test-bin
> > > ```
> > 
> > 
> > can solve the problem,But it's too cumbersome to execute every time
> > So，It is recommended to use docker to solve this problem。
> 
> i also meet the problem and use this method `printf '\x07' | dd of=test-bin bs=1 seek=160 count=1 conv=notrunc` fix it .
> 
> but i want to know that if gomonkey can fix it ?
+1

**Comment by eisenxp** [comment]
https://github.com/eisenxp/macos-golink-wrapper may help.

**Comment by aduan** [comment]
> https://github.com/eisenxp/macos-golink-wrapper may help.
It may be the best solution of this problem.

**Comment by JasonRock** [comment]
> https://github.com/eisenxp/macos-golink-wrapper may help.

It's work well!

**Comment by luckyzachary** [comment]
The best way is to use docker. 
Another way is https://github.com/eisenxp/macos-golink-wrapper . 
Thanks a lot .

**Comment by hsqStephenZhang** [comment]
i found a repository: https://github.com/eisenxp/macos-golink-wrapper
my colleagues have tried this method, all problems were settled

**Comment by sunblack110** [comment]
> 

it's not working at arm64 mac 12.0

**Comment by butcoder** [comment]
arm64 MacOS can use amd64 version go, I change to go1.16.11 darwin/amd64,and [https://github.com/eisenxp/macos-golink-wrapper](https://github.com/eisenxp/macos-golink-wrapper)

**Comment by LaryCaka** [comment]
谢谢哟，愿你开心每一天~

**Comment by guyunzh** [comment]
> arm64 MacOS可以使用amd64版本go，我换成go1.16.11 darwin/amd64，和https://github.com/eisenxp/macos-golink-wrapper

it will be get other question. such as: can not debug. 
golang version: go version go1.16.15 darwin/arm64
system : mac m1
goland:  2021.3(m1 soc)
如果把GOARCH改成amd64，会导致无法debug。我新遇到的问题

**Comment by LaryCaka** [comment]
谢谢哟，愿你开心每一天~

**Comment by agiledragon** [comment]
v2.11.0 has been released!

**Comment by LaryCaka** [comment]
谢谢哟，愿你开心每一天~

**Comment by LaryCaka** [comment]
谢谢哟，愿你开心每一天~
