### ISSUE TITLE
TestApplyPrivateMethod run fail

### ISSUE THREAD

**Issue by hesining** [agiledragon/gomonkey#119]
`go version
go1.19.5 linux/amd64
`

报错是：

`
 Line 21:
  Expected: 'unhappy'
  Actual:   'happy'
  (Should be equal)
  goroutine 6 [running]:
  	C:/Users/hesining/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/reporting/reports.go:143 +0x3c
  	C:/Users/hesining/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/reporting/reports.go:103 +0x5d
  	C:/Users/hesining/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:176 +0xa5
  	C:/Users/hesining/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/doc.go:125 +0x5a
  github.com/agiledragon/gomonkey/v2/test.TestApplyPrivateMethod.func1.1()
  	D:/code/gomonkey-master/gomonkey-master/test/apply_private_method_test.go:21 +0x22e
  	C:/Users/hesining/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/discovery.go:80 +0x1b
  	C:/Users/hesining/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:261 +0x177
  	C:/Users/hesining/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:163 +0x2c
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
  	C:/Users/hesining/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:97 +0x46a
  github.com/jtolds/gls.EnsureGoroutineId(0xc00007c780)
  	C:/Users/hesining/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:19 +0xfb
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc000064590, 0xc00007c720, 0xc000010108)
  	C:/Users/hesining/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:63 +0x16a
  	C:/Users/hesining/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:162 +0x2dc
  	C:/Users/hesining/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/doc.go:77 +0x75
  github.com/agiledragon/gomonkey/v2/test.TestApplyPrivateMethod.func1()
  	D:/code/gomonkey-master/gomonkey-master/test/apply_private_method_test.go:13 +0x66
  	C:/Users/hesining/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/discovery.go:80 +0x1b
  	C:/Users/hesining/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:261 +0x177
  	C:/Users/hesining/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:110 +0xdb
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
  	C:/Users/hesining/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:97 +0x46a
  github.com/jtolds/gls.EnsureGoroutineId.func1()
  	C:/Users/hesining/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:24 +0x22
  github.com/jtolds/gls._m(0x5e4540?, 0xc000048501?)
  	C:/Users/hesining/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:108 +0x22
  github.com/jtolds/gls.github_com_jtolds_gls_markS(0xc00007c630?, 0x0?)
  	C:/Users/hesining/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:56 +0x19
  github.com/jtolds/gls.addStackTag(...)
  	C:/Users/hesining/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:49
  github.com/jtolds/gls.EnsureGoroutineId(0xc00007c630?)
  	C:/Users/hesining/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:24 +0xd8
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc000064590, 0xc00007c5d0, 0xc0000660a0)
  	C:/Users/hesining/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:63 +0x16a
  	C:/Users/hesining/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:105 +0x22f
  	C:/Users/hesining/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/doc.go:75 +0x8b
  github.com/agiledragon/gomonkey/v2/test.TestApplyPrivateMethod(0x0?)
  	D:/code/gomonkey-master/gomonkey-master/test/apply_private_method_test.go:12 +0x79
  testing.tRunner(0xc000007a00, 0x6131c8)
  	C:/Program Files/Go/src/testing/testing.go:1446 +0x10b
  created by testing.(*T).Run
  	C:/Program Files/Go/src/testing/testing.go:1493 +0x35f
`

**Comment by hesining** [comment]
debug下正常，直接Run不正常

**Comment by paulschroeder-tomtom** [comment]
@hesining how did you solve the problem?

**Comment by agiledragon** [comment]
@wiselike Please take a look.

**Comment by xhd2015** [comment]
> [@xhd2015](https://github.com/xhd2015)
> 
> Yeah, did! But:
> 
> * I dont like the interface 😆 If you add methods just like gomonkey has I'm all in!
> * and as I can see it, I cannot mock 3rd party modules/methods/functions
> * and (but not sure if thats really necessary) I dont want to change my tooling (to `xgo test`), want to keep `go test`
> 
> a combination of reliability of your impl. and the ease of use of gomonkey qould be great.

@paulschroeder-tomtom fair points!
- about the interface, `xgo`'s is just more natural I think? here is a comparison I submitted for another project https://github.com/secretflow/kuscia/pull/661#issue-2979907865 . There is no cleanup needed, and by default goroutine-separated.
- glad you pointed out that third party library, the next patch version just addresses it, see https://github.com/xhd2015/xgo/pull/309
- yes you don't need to switch to xgo fully. `xgo setup` will output a `GOROOT` so you can use it as drop-in replacement for your `go`. Besides, if you prefix with `xgo exec ...`(next version) , you do not need to change anything.

**Comment by wiselike** [comment]
I will fix this issue, but could you let me know how to reproduce it? I see in the description that Golang uses the go1.19.5 linux/amd64 version, but the stack trace shows Windows. @agiledragon

**Comment by wiselike** [comment]
root@jim-virtual-machine:~/gomonkey# make test
bash ./ut.sh
--------Run test package: github.com/agiledragon/gomonkey/v2/test
go: downloading github.com/smartystreets/goconvey v1.6.4
go: downloading github.com/jtolds/gls v4.20.0+incompatible
go: downloading github.com/smartystreets/assertions v0.0.0-20180927180507-b2de0cb4f26d
=== RUN   TestApplyFuncReturn

  TestApplyFuncReturn
    declares the values to be returned ✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔


40 total assertions

--- PASS: TestApplyFuncReturn (0.00s)
=== RUN   TestApplyFuncSeq

  TestApplyFuncSeq
    default times is 1 ✔✔✔✔✔✔
    retry succ util the third times ✔✔✔✔
    batch operations failed on the third time ✔✔✔✔✔


55 total assertions

--- PASS: TestApplyFuncSeq (0.00s)
=== RUN   TestApplyFunc

  TestApplyFunc
    one func for succ ✔✔
    one func for succ with origin ✔✔
    one func for succ with origin inside
    one func for fail ✔✔
    two funcs ✔✔✔
    two funcs with origin ✔✔✔✔
    input and output param ✔✔✔
    repeat patch same func ✔✔✔✔✔✔
    declare partial args ✔✔✔✔✔✔✔


84 total assertions

--- PASS: TestApplyFunc (0.00s)
=== RUN   TestApplyFuncVarReturn

  TestApplyFuncVarReturn
    declares the values to be returned ✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔


124 total assertions

--- PASS: TestApplyFuncVarReturn (0.00s)
=== RUN   TestApplyFuncVarSeq

  TestApplyFuncVarSeq
    default times is 1 ✔✔✔✔✔✔
    retry succ util the third times ✔✔✔✔
    batch operations failed on the third time ✔✔✔✔✔


139 total assertions

--- PASS: TestApplyFuncVarSeq (0.00s)
=== RUN   TestApplyFuncVar

  TestApplyFuncVar
    for succ ✔✔
    for fail ✔


142 total assertions

--- PASS: TestApplyFuncVar (0.00s)
=== RUN   TestApplyGlobalVar

  TestApplyGlobalVar
    change ✔
    recover ✔


144 total assertions

--- PASS: TestApplyGlobalVar (0.00s)
=== RUN   TestApplyInterfaceReused

  TestApplyInterfaceReused
    TestApplyInterface ✔✔
    TestApplyInterfaceSeq ✔✔✔✔✔✔
    the arg type can be interface ✔✔


154 total assertions

--- PASS: TestApplyInterfaceReused (0.00s)
=== RUN   TestApplyMethodFunc

  TestApplyMethodFunc
    for succ Slice: Add elem: 1 succ
✔✔Slice: Remove elem: 1 succ
✔✔
    for origin Slice: Add elem: 1 succ
✔Slice: Add elem: 1 already exist
✔Slice: Remove elem: 1 succ
✔✔
    for already exist Slice: Add elem: 2 succ
✔✔Slice: Remove elem: 2 succ
✔✔
    two methods Slice: Add elem: 3 succ
✔✔✔✔✔Slice: Remove elem: 3 succ

    one func and one method Slice: Add elem: 4 succ
✔✔✔✔✔✔Slice: Remove elem: 4 succ

    for variadic method Slice: Append elem: [1 2 3] succ
✔✔✔


180 total assertions

--- PASS: TestApplyMethodFunc (0.00s)
=== RUN   TestApplyMethodReturn

  TestApplyMethodReturn
    declares the values to be returned ✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔


220 total assertions

--- PASS: TestApplyMethodReturn (0.00s)
=== RUN   TestApplyMethodSeq

  TestApplyMethodSeq
    default times is 1 ✔✔✔✔✔✔
    retry succ util the third times ✔✔✔✔
    batch operations failed on the third time ✔✔✔✔✔


235 total assertions

--- PASS: TestApplyMethodSeq (0.00s)
=== RUN   TestApplyMethod

  TestApplyMethod
    for succ Slice: Add elem: 1 succ
✔✔Slice: Remove elem: 1 succ
✔✔
    for already exist Slice: Add elem: 2 succ
✔✔Slice: Remove elem: 2 succ
✔✔
    two methods Slice: Add elem: 3 succ
✔✔✔✔✔Slice: Remove elem: 3 succ

    one func and one method Slice: Add elem: 4 succ
✔✔✔✔✔✔Slice: Remove elem: 4 succ



254 total assertions

--- PASS: TestApplyMethod (0.00s)
=== RUN   TestApplyPrivateMethod

  TestApplyPrivateMethod
    patch private pointer method in the different package ✔
    patch private value method in the different package ✔
    repeat patch same method ✔✔✔


259 total assertions

--- PASS: TestApplyPrivateMethod (0.00s)
=== RUN   TestPatchPair

  TestPatchPair
    TestPatchPair ✔✔✔✔✔


264 total assertions

--- PASS: TestPatchPair (0.00s)
PASS
coverage: 81.5% of statements in ./...
ok      github.com/agiledragon/gomonkey/v2/test 0.012s  coverage: 81.5% of statements in ./...
--------Finish test package: github.com/agiledragon/gomonkey/v2/test
--------Run test package: github.com/agiledragon/gomonkey/v2/test/dsl_test
=== RUN   TestPbBuilderFunc

  TestPbBuilderFunc
    first dsl ✔✔✔


3 total assertions

--- PASS: TestPbBuilderFunc (0.00s)
PASS
coverage: 27.8% of statements in ./...
ok      github.com/agiledragon/gomonkey/v2/test/dsl_test        0.003s  coverage: 27.8% of statements in ./...
--------Finish test package: github.com/agiledragon/gomonkey/v2/test/dsl_test
root@jim-virtual-machine:~/gomonkey# go version
go version go1.19.5 linux/amd64

**Comment by agiledragon** [comment]
@wiselike  Well Done!

A likely cause of the issue was that inlining was not disabled. Refer to the description in the README:  

> gomonkey fails to patch a function or a member method if inlining is enabled. Please run your tests with inlining disabled by adding the command line argument `-gcflags=-l` (for Go versions below 1.10) or `-gcflags=all=-l` (for Go 1.10 and above).

**Comment by paulschroeder-tomtom** [comment]
@agiledragon yes, thats it. Missed that 😔, sorry.

**Comment by paulschroeder-tomtom** [comment]
@xhd2015 
> > [@xhd2015](https://github.com/xhd2015)
> > Yeah, did! But:
> > 
> > * I dont like the interface 😆 If you add methods just like gomonkey has I'm all in!
> > * and as I can see it, I cannot mock 3rd party modules/methods/functions
> > * and (but not sure if thats really necessary) I dont want to change my tooling (to `xgo test`), want to keep `go test`
> > 
> > a combination of reliability of your impl. and the ease of use of gomonkey qould be great.
> 
> [@paulschroeder-tomtom](https://github.com/paulschroeder-tomtom) fair points!
> 
> * about the interface, `xgo`'s is just more natural I think? here is a comparison I submitted for another project [test: simplify mock with xgo secretflow/kuscia#661 (comment)](https://github.com/secretflow/kuscia/pull/661#issue-2979907865) . There is no cleanup needed, and by default goroutine-separated.
> * glad you pointed out that third party library, the next patch version just addresses it, see [move runtime_link_template.go to xgo/runtime to ensure maximal API compatibility, introduce a minimal type checker to scan mock.Patch calls xhd2015/xgo#309](https://github.com/xhd2015/xgo/pull/309)
> * yes you don't need to switch to xgo fully. `xgo setup` will output a `GOROOT` so you can use it as drop-in replacement for your `go`. Besides, if you prefix with `xgo exec ...`(next version) , you do not need to change anything.

I see, will have another look. But still there's `xgo` instead of `go` and I would have to do a lot of convincing in my team to make them use that instead of regular `go`.

With github.com/agiledragon/gomonkey this is much less impactful. Just changing some tests and flags is fine but swapping the tooling all the alarms in the team would go off.
