### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by liangjingkanji** [agiledragon/gomonkey#70]
Line 19: - permission denied 
goroutine 4 [running]:

发生在: 
- MacOS 11.6.1 (ARM64 M1 以及 X86都如此)
- 运行`GoMonkey`的最新Demo
- 使用的gomonkey 2.2.0

描述:
- 使用`GOARCH=amd64`可以解决, 但是无法debug很不幸.
- 在Linux/Windows都是正常
- 尝试过 [macos-golink-wrapper](https://github.com/eisenxp/macos-golink-wrapper) 方案无效

**Comment by sunblack110** [comment]
is it fixed, It was the some in my MacOS 12.0 monterey 

panic: permission denied [recovered]
	panic: permission denied

goroutine 34 [running]:
testing.tRunner.func1.2({0x100ec4c00, 0x101187e88})
	/Users/chengfeng.han/Apps/go/sdk/go1.17.3/src/testing/testing.go:1209 +0x258
testing.tRunner.func1(0x140004829c0)
	/Users/chengfeng.han/Apps/go/sdk/go1.17.3/src/testing/testing.go:1212 +0x284
panic({0x100ec4c00, 0x101187e88})
	/Users/chengfeng.han/Apps/go/sdk/go1.17.3/src/runtime/panic.go:1038 +0x21c
github.com/agiledragon/gomonkey/v2.modifyBinary(0x100c77320, {0x140004ac090, 0x18, 0x18})
	/Users/chengfeng.han/Work/工作事业/产品管理/葫芦小智/开发/源代码/hulu/hulu-edge-os/vendor/github.com/agiledragon/gomonkey/v2/modify_binary_darwin.go:11 +0x134

**Comment by liangjingkanji** [comment]
Suggest to give up

**Comment by BardVolta** [comment]
https://github.com/eisenxp/macos-golink-wrapper

**Comment by xnnyeYp** [comment]
我也遇到这个问题了

**Comment by agiledragon** [comment]
> copy(function, bytes)
> 
> err = syscall.Mprotect(page, syscall.PROT_READ|syscall.PROT_EXEC)
> if err != nil {
>     panic(err)
> }
> ```
> 
> }`
> 
> "github.com/agiledragon/gomonkey/v2" modify_binary_darwin.go

Please others  who has the same problem test it using this method.

**Comment by Zeahow** [comment]
> it is fixed by a very easy way.
> 
> err := syscall.Mprotect(page, syscall.PROT_READ|syscall.PROT_WRITE|syscall.PROT_EXEC)
> 
> change to
> 
> err := syscall.Mprotect(page, syscall.PROT_READ|syscall.PROT_WRITE)
> 
> in the function `func modifyBinary(target uintptr, bytes []byte) { function := entryAddress(target, len(bytes))
> 
> ```
> page := entryAddress(pageStart(target), syscall.Getpagesize())
> err := syscall.Mprotect(page, syscall.PROT_READ|syscall.PROT_WRITE|syscall.PROT_EXEC)
> if err != nil {
>     panic(err)
> }
> copy(function, bytes)
> 
> err = syscall.Mprotect(page, syscall.PROT_READ|syscall.PROT_EXEC)
> if err != nil {
>     panic(err)
> }
> ```
> 
> }`
> 
> "github.com/agiledragon/gomonkey/v2" modify_binary_darwin.go

still got "permission denied"

![image](https://user-images.githubusercontent.com/26248788/158777371-403324a1-b352-444a-b32c-2c1063e89ed1.png)

**Comment by sunblack110** [comment]
I don't why it's working for me ....

**Comment by jonathanrhodes** [comment]
I tried this and it...sort of worked? However, there seemed to be some sort of timing issue - I noticed that the patch reset wasn't taking effect.

Adding a small sleep seemed to fix that, but without understanding the problem, I don't trust that as a solution. For reference, here was my full `modifyBinary()` from `modify_binary_darwin.go`:

```
func modifyBinary(target uintptr, bytes []byte) {
	function := entryAddress(target, len(bytes))
	err := mprotectCrossPage(target, len(bytes), syscall.PROT_READ|syscall.PROT_WRITE)
	if err != nil {
		panic(err)
	}
	copy(function, bytes)
	err = mprotectCrossPage(target, len(bytes), syscall.PROT_READ|syscall.PROT_EXEC)
	if err != nil {
		panic(err)
	}
	time.Sleep(time.Millisecond)
}
```

----

After this change, the tests in `gomonkey/test` suite failed in similar ways between my M1 and non-M1 machines.

More specifically, everything passed except `apply_private_method_test.go`. On M1, I get an `unexpected fault address`, whereas on non-M1 I get `retrieve method by name failed`.

**Comment by butcoder** [comment]
arm64 MacOS can use amd64 version go, I change to go1.16.11 darwin/amd64,and [https://github.com/eisenxp/macos-golink-wrapper](https://github.com/eisenxp/macos-golink-wrapper)

**Comment by agiledragon** [comment]
Good job!

**Comment by liangjingkanji** [comment]
> arm64 MacOS can use amd64 version go, I change to go1.16.11 darwin/amd64,and https://github.com/eisenxp/macos-golink-wrapper

This will make it impossible to debug with breakpoints

**Comment by Tifinity** [comment]
请问这个问题解决了吗？只能换 amd64 版本的 go 是吗

**Comment by liangjingkanji** [comment]
换arm64无法断点调试, 而且编译性能差, 基本上等于没解决

**Comment by wudaijun** [comment]
> 

你说的是amd64吧

**Comment by Tifinity** [comment]
好吧 ·～·

**Comment by xhd2015** [comment]
we have implemented a compile-time code rewrite to support any function mock, in general it does not rely on any architecture hack, anyone interested ? we're using it to bootstrap our test cases, wish it could finally be a solution to function-level mock problems.

**Comment by agiledragon** [comment]
@xhd2015 Show your code.

**Comment by xhd2015** [comment]
> @xhd2015 Show your code.

@agiledragon  Hi guy I made it here: [https://github.com/xhd2015/go-mock](https://github.com/xhd2015/go-mock), the brief idea is take from [https://go.dev/blog/cover](https://go.dev/blog/cover), that we insert a Trap call in beginning of each function's body, to catch the control flow of the original function, meanwhile does not change the line layout of the original files so that debugging info are still accurate.

**Comment by LeslieLeung** [comment]
> I tried this and it...sort of worked? However, there seemed to be some sort of timing issue - I noticed that the patch reset wasn't taking effect.
> 
> Adding a small sleep seemed to fix that, but without understanding the problem, I don't trust that as a solution. For reference, here was my full `modifyBinary()` from `modify_binary_darwin.go`:
> 
> ```
> func modifyBinary(target uintptr, bytes []byte) {
> 	function := entryAddress(target, len(bytes))
> 	err := mprotectCrossPage(target, len(bytes), syscall.PROT_READ|syscall.PROT_WRITE)
> 	if err != nil {
> 		panic(err)
> 	}
> 	copy(function, bytes)
> 	err = mprotectCrossPage(target, len(bytes), syscall.PROT_READ|syscall.PROT_EXEC)
> 	if err != nil {
> 		panic(err)
> 	}
> 	time.Sleep(time.Millisecond)
> }
> ```
> 
> After this change, the tests in `gomonkey/test` suite failed in similar ways between my M1 and non-M1 machines.
> 
> More specifically, everything passed except `apply_private_method_test.go`. On M1, I get an `unexpected fault address`, whereas on non-M1 I get `retrieve method by name failed`.

I am using the original bouke monkey(which has the very much same code here). Still looking for a solution.

**Comment by zzpwestlife** [comment]
Waiting for a solution

**Comment by cahan1013** [comment]
Any possibility we get a solution? @agiledragon

**Comment by upidea** [comment]
Also, any solution for this question? @agiledragon

**Comment by 719010539** [comment]
> it is fixed by a very easy way.
> 
> err := syscall.Mprotect(page, syscall.PROT_READ|syscall.PROT_WRITE|syscall.PROT_EXEC)
> 
> change to
> 
> err := syscall.Mprotect(page, syscall.PROT_READ|syscall.PROT_WRITE)
> 
> in the function `func modifyBinary(target uintptr, bytes []byte) { function := entryAddress(target, len(bytes))
> 
> ```
> page := entryAddress(pageStart(target), syscall.Getpagesize())
> err := syscall.Mprotect(page, syscall.PROT_READ|syscall.PROT_WRITE|syscall.PROT_EXEC)
> if err != nil {
>     panic(err)
> }
> copy(function, bytes)
> 
> err = syscall.Mprotect(page, syscall.PROT_READ|syscall.PROT_EXEC)
> if err != nil {
>     panic(err)
> }
> ```
> 
> }`
> 
> "github.com/agiledragon/gomonkey/v2" modify_binary_darwin.go

亲测有效，在别的地方看到有说因为安全原因无法同时写和执行，把代码复制出来试了一下确实成功了。

func modifyBinary(target uintptr, bytes []byte) {
	function := entryAddress(target, len(bytes))

	page := entryAddress(pageStart(target), syscall.Getpagesize())
	err := syscall.Mprotect(page, syscall.PROT_READ|syscall.PROT_WRITE)
	if err != nil {
		panic(err)
	}
	copy(function, bytes)

	err = syscall.Mprotect(page, syscall.PROT_READ|syscall.PROT_EXEC)
	if err != nil {
		panic(err)
	}
}

**Comment by Nomango** [comment]
解决了请踢我一下

**Comment by 719010539** [comment]
收到!

**Comment by lingxialingdu** [comment]
on macos, you can try command [go test -ldflags="-extldflags="-Wl,-segprot,__TEXT,rwx,rx""]，go test command with option extldflags. which have same effact with https://github.com/eisenxp/macos-golink-wrapper

**Comment by vimt** [comment]
I do some [test](https://gist.github.com/vimt/a165366ec833db84c7c5e309d342fb7b) of mprotect on m1.

conclusion: m1 memory page can't has W+X at some time, and TEXT segment must have X, so we can't write TEXT segment😭

`GOARCH=amd64` is the only way

**Comment by 719010539** [comment]
收到!

**Comment by jinshanwang** [comment]
> it is fixed by a very easy way.
> 
> err := syscall.Mprotect(page, syscall.PROT_READ|syscall.PROT_WRITE|syscall.PROT_EXEC)
> 
> change to
> 
> err := syscall.Mprotect(page, syscall.PROT_READ|syscall.PROT_WRITE)
> 
> in the function `func modifyBinary(target uintptr, bytes []byte) { function := entryAddress(target, len(bytes))
> 
> ```
> page := entryAddress(pageStart(target), syscall.Getpagesize())
> err := syscall.Mprotect(page, syscall.PROT_READ|syscall.PROT_WRITE|syscall.PROT_EXEC)
> if err != nil {
>     panic(err)
> }
> copy(function, bytes)
> 
> err = syscall.Mprotect(page, syscall.PROT_READ|syscall.PROT_EXEC)
> if err != nil {
>     panic(err)
> }
> ```
> 
> }`
> 
> "github.com/agiledragon/gomonkey/v2" modify_binary_darwin.go

thank you so much mate

**Comment by benyingY** [comment]
got same issue
apple M1

**Comment by benyingY** [comment]
> on macos, you can try command [go test -ldflags="-extldflags="-Wl,-segprot,__TEXT,rwx,rx""]，go test command with option extldflags. which have same effect with https://github.com/eisenxp/macos-golink-wrapper, but do not need wrap go link

not work for me

**Comment by green4984** [comment]
Test ok at Mac M1 13.2.1
Please follow step below to solve problem "permission denied"
follow this issues steam solution and test at Mac M1. 

+ Enjoy it and save your life, I donnot know why!

---

1. find this file `modify_binary_darwin.go` in your `GoProjects/pkg`
2. currently gomonkey version is v2@v2.9.0, please replace this file with code below directly
```
package gomonkey

import (
	"syscall"
	"time"
)

func modifyBinary(target uintptr, bytes []byte) {
	function := entryAddress(target, len(bytes))
	err := mprotectCrossPage(target, len(bytes), syscall.PROT_READ|syscall.PROT_WRITE)
	if err != nil {
		panic(err)
	}
	copy(function, bytes)
	err = mprotectCrossPage(target, len(bytes), syscall.PROT_READ|syscall.PROT_EXEC)
	if err != nil {
		panic(err)
	}
	time.Sleep(time.Millisecond)
}

func mprotectCrossPage(addr uintptr, length int, prot int) error {
	pageSize := syscall.Getpagesize()
	for p := pageStart(addr); p < addr+uintptr(length); p += uintptr(pageSize) {
		page := entryAddress(p, pageSize)
		if err := syscall.Mprotect(page, prot); err != nil {
			return err
		}
	}
	return nil
}


```

**Comment by aloisio31** [comment]
> on macos, you can try command [go test -ldflags="-extldflags="-Wl,-segprot,__TEXT,rwx,rx""]，go test command with option extldflags. which have same effect with https://github.com/eisenxp/macos-golink-wrapper, but do not need wrap go link

this works for me!

**Comment by 719010539** [comment]
收到!

**Comment by Cronusl** [comment]
> 

get error on m1, could not import time (open : no such file or directory)

**Comment by vimt** [comment]
> Test ok at Mac M1 13.2.1 Please follow step below to solve problem "permission denied" follow this issues steam solution and test at Mac M1.
> 
> * Enjoy it and save your life, I donnot know why!
> 
> 1. find this file `modify_binary_darwin.go` in your `GoProjects/pkg`
> 2. currently gomonkey version is v2@v2.9.0, please replace this file with code below directly
> 
> ```
> package gomonkey
> 
> import (
> 	"syscall"
> 	"time"
> )
> 
> func modifyBinary(target uintptr, bytes []byte) {
> 	function := entryAddress(target, len(bytes))
> 	err := mprotectCrossPage(target, len(bytes), syscall.PROT_READ|syscall.PROT_WRITE)
> 	if err != nil {
> 		panic(err)
> 	}
> 	copy(function, bytes)
> 	err = mprotectCrossPage(target, len(bytes), syscall.PROT_READ|syscall.PROT_EXEC)
> 	if err != nil {
> 		panic(err)
> 	}
> 	time.Sleep(time.Millisecond)
> }
> 
> func mprotectCrossPage(addr uintptr, length int, prot int) error {
> 	pageSize := syscall.Getpagesize()
> 	for p := pageStart(addr); p < addr+uintptr(length); p += uintptr(pageSize) {
> 		page := entryAddress(p, pageSize)
> 		if err := syscall.Mprotect(page, prot); err != nil {
> 			return err
> 		}
> 	}
> 	return nil
> }
> ```

Not work for me :(

My env: 
M1 Pro, 13.3.1, Go, go1.20.1 darwin/arm64

I tried with this file

```golang
package main

import (
	"fmt"
	"github.com/agiledragon/gomonkey/v2"
)

//go:noinline
func Foo() {
	fmt.Println("not patch")
}

func main() {
	gomonkey.ApplyFunc(Foo, func() {
		fmt.Println("patched")
	})
	Foo()
}
```

when I run this file, I got `segmentation fault`
```shell
$ go run test_gomonkey.go 
signal: segmentation fault
```

**Comment by FLAGLORD** [comment]
> Test ok at Mac M1 13.2.1 Please follow step below to solve problem "permission denied" follow this issues steam solution and test at Mac M1.
> 
> * Enjoy it and save your life, I donnot know why!
> 
> 1. find this file `modify_binary_darwin.go` in your `GoProjects/pkg`
> 2. currently gomonkey version is v2@v2.9.0, please replace this file with code below directly
> 
> ```
> package gomonkey
> 
> import (
> 	"syscall"
> 	"time"
> )
> 
> func modifyBinary(target uintptr, bytes []byte) {
> 	function := entryAddress(target, len(bytes))
> 	err := mprotectCrossPage(target, len(bytes), syscall.PROT_READ|syscall.PROT_WRITE)
> 	if err != nil {
> 		panic(err)
> 	}
> 	copy(function, bytes)
> 	err = mprotectCrossPage(target, len(bytes), syscall.PROT_READ|syscall.PROT_EXEC)
> 	if err != nil {
> 		panic(err)
> 	}
> 	time.Sleep(time.Millisecond)
> }
> 
> func mprotectCrossPage(addr uintptr, length int, prot int) error {
> 	pageSize := syscall.Getpagesize()
> 	for p := pageStart(addr); p < addr+uintptr(length); p += uintptr(pageSize) {
> 		page := entryAddress(p, pageSize)
> 		if err := syscall.Mprotect(page, prot); err != nil {
> 			return err
> 		}
> 	}
> 	return nil
> }
> ```

It works for me, but I can only use it when ARCH is arm64. If I switch to amd64, it produces the same error. It may introduce compatibility problems

**Comment by xialeistudio** [comment]
> I tried this and it...sort of worked? However, there seemed to be some sort of timing issue - I noticed that the patch reset wasn't taking effect.
> 
> Adding a small sleep seemed to fix that, but without understanding the problem, I don't trust that as a solution. For reference, here was my full `modifyBinary()` from `modify_binary_darwin.go`:
> 
> ```
> func modifyBinary(target uintptr, bytes []byte) {
> 	function := entryAddress(target, len(bytes))
> 	err := mprotectCrossPage(target, len(bytes), syscall.PROT_READ|syscall.PROT_WRITE)
> 	if err != nil {
> 		panic(err)
> 	}
> 	copy(function, bytes)
> 	err = mprotectCrossPage(target, len(bytes), syscall.PROT_READ|syscall.PROT_EXEC)
> 	if err != nil {
> 		panic(err)
> 	}
> 	time.Sleep(time.Millisecond)
> }
> ```
> 
> After this change, the tests in `gomonkey/test` suite failed in similar ways between my M1 and non-M1 machines.
> 
> More specifically, everything passed except `apply_private_method_test.go`. On M1, I get an `unexpected fault address`, whereas on non-M1 I get `retrieve method by name failed`.

Works for my M1, thank you very much!

**Comment by 719010539** [comment]
收到!

**Comment by spacewander** [comment]
@agiledragon 
Would you like to apply this fix to the code?
It's cumbersome to apply this patch by the user each time we use gomonkey.

**Comment by 719010539** [comment]
收到!

**Comment by cavanwang** [comment]
> on macos, you can try command [go test -ldflags="-extldflags="-Wl,-segprot,__TEXT,rwx,rx""]，go test command with option extldflags. which have same effect with https://github.com/eisenxp/macos-golink-wrapper, but do not need wrap go link

It works fine for me on mac os with AMD64.

**Comment by 719010539** [comment]
收到!

**Comment by kangour** [comment]
m2 同样有这个问题。
go1.21.0 darwin/arm64
gomonkey/v2 v2.3.1

**Comment by 719010539** [comment]
收到!

**Comment by Zjmainstay** [comment]
> Test ok at Mac M1 13.2.1 Please follow step below to solve problem "permission denied" follow this issues steam solution and test at Mac M1.
> 
> * Enjoy it and save your life, I donnot know why!
> 
> 1. find this file `modify_binary_darwin.go` in your `GoProjects/pkg`
> 2. currently gomonkey version is v2@v2.9.0, please replace this file with code below directly
> 
> ```
> package gomonkey
> 
> import (
> 	"syscall"
> 	"time"
> )
> 
> func modifyBinary(target uintptr, bytes []byte) {
> 	function := entryAddress(target, len(bytes))
> 	err := mprotectCrossPage(target, len(bytes), syscall.PROT_READ|syscall.PROT_WRITE)
> 	if err != nil {
> 		panic(err)
> 	}
> 	copy(function, bytes)
> 	err = mprotectCrossPage(target, len(bytes), syscall.PROT_READ|syscall.PROT_EXEC)
> 	if err != nil {
> 		panic(err)
> 	}
> 	time.Sleep(time.Millisecond)
> }
> 
> func mprotectCrossPage(addr uintptr, length int, prot int) error {
> 	pageSize := syscall.Getpagesize()
> 	for p := pageStart(addr); p < addr+uintptr(length); p += uintptr(pageSize) {
> 		page := entryAddress(p, pageSize)
> 		if err := syscall.Mprotect(page, prot); err != nil {
> 			return err
> 		}
> 	}
> 	return nil
> }
> ```

这个测试可用，但是这里的表述有点问题，我补充一下：
1、只需要修改文件`modify_binary_darwin.go`第7行，删除参数：syscall.PROT_EXEC
最终：`err := mprotectCrossPage(target, len(bytes), syscall.PROT_READ|syscall.PROT_WRITE)`
2、使用go test -gcflags=all=-l 进行测试

**Comment by 2264381489** [comment]
> on macos, you can try command [go test -ldflags="-extldflags="-Wl,-segprot,__TEXT,rwx,rx""]，go test command with option extldflags. which have same effect with https://github.com/eisenxp/macos-golink-wrapper, but do not need wrap go link

its good for me

**Comment by zplzpl** [comment]
> > Test ok at Mac M1 13.2.1 Please follow step below to solve problem "permission denied" follow this issues steam solution and test at Mac M1.
> > 
> > * Enjoy it and save your life, I donnot know why!
> > 
> > 
> > 1. find this file `modify_binary_darwin.go` in your `GoProjects/pkg`
> > 2. currently gomonkey version is v2@v2.9.0, please replace this file with code below directly
> > 
> > ```
> > package gomonkey
> > 
> > import (
> > 	"syscall"
> > 	"time"
> > )
> > 
> > func modifyBinary(target uintptr, bytes []byte) {
> > 	function := entryAddress(target, len(bytes))
> > 	err := mprotectCrossPage(target, len(bytes), syscall.PROT_READ|syscall.PROT_WRITE)
> > 	if err != nil {
> > 		panic(err)
> > 	}
> > 	copy(function, bytes)
> > 	err = mprotectCrossPage(target, len(bytes), syscall.PROT_READ|syscall.PROT_EXEC)
> > 	if err != nil {
> > 		panic(err)
> > 	}
> > 	time.Sleep(time.Millisecond)
> > }
> > 
> > func mprotectCrossPage(addr uintptr, length int, prot int) error {
> > 	pageSize := syscall.Getpagesize()
> > 	for p := pageStart(addr); p < addr+uintptr(length); p += uintptr(pageSize) {
> > 		page := entryAddress(p, pageSize)
> > 		if err := syscall.Mprotect(page, prot); err != nil {
> > 			return err
> > 		}
> > 	}
> > 	return nil
> > }
> > ```
> 
> 这个测试可用，但是这里的表述有点问题，我补充一下： 1、只需要修改文件`modify_binary_darwin.go`第7行，删除参数：syscall.PROT_EXEC 最终：`err := mprotectCrossPage(target, len(bytes), syscall.PROT_READ|syscall.PROT_WRITE)` 2、使用go test -gcflags=all=-l 进行测试

work for me

**Comment by jinshanwang** [comment]
thanks







                       
Original
                       
                     

From:"Zpl"< ***@***.*** &gt;;

Date:2023/10/14 23:56

To:"agiledragon/gomonkey"< ***@***.*** &gt;;

CC:"Joseph"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

Subject:Re: [agiledragon/gomonkey] macOS permission denied (Issue #70)




   
Test ok at Mac M1 13.2.1 Please follow step below to solve problem "permission denied" follow this issues steam solution and test at Mac M1.
  
Enjoy it and save your life, I donnot know why!
   
find this file modify_binary_darwin.go in your GoProjects/pkg
 
currently gomonkey version is ***@***.***, please replace this file with code below directly
  package gomonkey import ( 	"syscall" 	"time" ) func modifyBinary(target uintptr, bytes []byte) { 	function := entryAddress(target, len(bytes)) 	err := mprotectCrossPage(target, len(bytes), syscall.PROT_READ|syscall.PROT_WRITE) 	if err != nil { 		panic(err) 	} 	copy(function, bytes) 	err = mprotectCrossPage(target, len(bytes), syscall.PROT_READ|syscall.PROT_EXEC) 	if err != nil { 		panic(err) 	} 	time.Sleep(time.Millisecond) } func mprotectCrossPage(addr uintptr, length int, prot int) error { 	pageSize := syscall.Getpagesize() 	for p := pageStart(addr); p < addr+uintptr(length); p += uintptr(pageSize) { 		page := entryAddress(p, pageSize) 		if err := syscall.Mprotect(page, prot); err != nil { 			return err 		} 	} 	return nil }   
这个测试可用，但是这里的表述有点问题，我补充一下： 1、只需要修改文件modify_binary_darwin.go第7行，删除参数：syscall.PROT_EXEC 最终：err := mprotectCrossPage(target, len(bytes), syscall.PROT_READ|syscall.PROT_WRITE) 2、使用go test -gcflags=all=-l 进行测试
  
work for me

**Comment by LargeOrange** [comment]
> > Test ok at Mac M1 13.2.1 Please follow step below to solve problem "permission denied" follow this issues steam solution and test at Mac M1.
> > 
> > * Enjoy it and save your life, I donnot know why!
> > 
> > 
> > 1. find this file `modify_binary_darwin.go` in your `GoProjects/pkg`
> > 2. currently gomonkey version is v2@v2.9.0, please replace this file with code below directly
> > 
> > ```
> > package gomonkey
> > 
> > import (
> > 	"syscall"
> > 	"time"
> > )
> > 
> > func modifyBinary(target uintptr, bytes []byte) {
> > 	function := entryAddress(target, len(bytes))
> > 	err := mprotectCrossPage(target, len(bytes), syscall.PROT_READ|syscall.PROT_WRITE)
> > 	if err != nil {
> > 		panic(err)
> > 	}
> > 	copy(function, bytes)
> > 	err = mprotectCrossPage(target, len(bytes), syscall.PROT_READ|syscall.PROT_EXEC)
> > 	if err != nil {
> > 		panic(err)
> > 	}
> > 	time.Sleep(time.Millisecond)
> > }
> > 
> > func mprotectCrossPage(addr uintptr, length int, prot int) error {
> > 	pageSize := syscall.Getpagesize()
> > 	for p := pageStart(addr); p < addr+uintptr(length); p += uintptr(pageSize) {
> > 		page := entryAddress(p, pageSize)
> > 		if err := syscall.Mprotect(page, prot); err != nil {
> > 			return err
> > 		}
> > 	}
> > 	return nil
> > }
> > ```
> 
> 这个测试可用，但是这里的表述有点问题，我补充一下： 1、只需要修改文件`modify_binary_darwin.go`第7行，删除参数：syscall.PROT_EXEC 最终：`err := mprotectCrossPage(target, len(bytes), syscall.PROT_READ|syscall.PROT_WRITE)` 2、使用go test -gcflags=all=-l 进行测试

worked for me.

**Comment by agiledragon** [comment]
v2.11.0 has been released!

**Comment by Nomango** [comment]
> v2.11.0 has been released!

It works on my M2 Mac! 🎉

**Comment by gaochuwuhan** [comment]
The solution for mac with intel:
add go tool args: **`-gcflags "all=-N -l" -ldflags="-extldflags="-Wl,-segprot,__TEXT,rwx,rx""`**

**Comment by arfan** [comment]
in mac M1 I get `Process finished with the exit code 139 (interrupted by signal 11: SIGSEGV)`

my code is
```package main

import (
	"fmt"
	"github.com/agiledragon/gomonkey/v2"
)

func add(a, b int) int {
	return a + b
}

func main() {
	fmt.Println(add(5, 2))
	gomonkey.ApplyFunc(add, func(a, b int) int {
		return a * b
	})
	fmt.Println(add(5, 2))
}
```

im using version 2.11.0, golang 1.20.5

**Comment by agiledragon** [comment]
> I update gomonkey from v2.9.0 to v2.11.0 and finally fix this problem!
> 
> Additional info:
> 
> 1. m1 pro
> 2. go 1.12
> 3. goconvey 1.7.2

@myzhan Good news!

**Comment by sidgwick** [comment]
<img width="938" alt="image" src="https://github.com/agiledragon/gomonkey/assets/3956468/c07204fc-7c27-4152-96c3-f1b9ecfa4248">

**Comment by 719010539** [comment]
收到!

**Comment by xhd2015** [comment]
It seems that gomonkey is unstable. People are getting frequently trapped into this error. xgo has solved all the compatibility issues. If anyone want to try, check https://github.com/xhd2015/xgo for more details.
